app_banco:
    resource: "@AppBundle/Controller/BancoController.php"
    type:     annotation

app_tipocuenta:
    resource: "@AppBundle/Controller/TipocuentaController.php"
    type:     annotation


app_actividad:
    resource: "@AppBundle/Controller/ActividadController.php"
    type:     annotation

app_bitacora:
    resource: "@AppBundle/Controller/BitacoraController.php"
    type:     annotation

app_solicitudss:
    resource: "@AppBundle/Controller/SolicitudssController.php"
    type:     annotation

website:
    resource: "@AppBundle/Controller/"
    type:     annotation

salex_user:
    resource: "@SalexUserBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

avanzu_admin:
    resource: "@AvanzuAdminThemeBundle/Resources/config/routes.yml"

#FOSUserBundle routing file
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# image processing bundle
# https://github.com/liip/LiipImagineBundle
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

avanzu_admin_profile:
    path: /profile
